server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assinaturas?createDatabaseIfNotExist=true
    username: root
    password: admin
    
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


info:
  app:
    name: Assinaturas Globoplay
    description: Aplicação para realizar novas assinaturas
    version: 0.1.0


management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: health, info, env, flyway
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    flyway:
      enabled: true