INSERT INTO status(name)
SELECT * FROM (SELECT 'SUBSCRIPTION_PURCHASED') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM status WHERE name = 'SUBSCRIPTION_PURCHASED'
) LIMIT 1;

INSERT INTO status(name)
SELECT * FROM (SELECT 'SUBSCRIPTION_CANCELED') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM status WHERE name = 'SUBSCRIPTION_CANCELED'
) LIMIT 1;

INSERT INTO status(name)
SELECT * FROM (SELECT 'SUBSCRIPTION_RESTARTED') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM status WHERE name = 'SUBSCRIPTION_RESTARTED'
) LIMIT 1;